### ISSUE TITLE
Train own model

### ISSUE THREAD

**Issue by zuob-1861523** [YoungSeng/DiffuseStyleGesture#14]
Hi, thank you for sharing the code. Was following the process and trying to train my own model. However, I downloaded the processed datasets so I assume I did not need to run zeggs_data_to_lmdb.py. Is this correct? If this is the case when I try to run end2end.py the path is problematic. I put the downloaded trimmed/train under processed_v1/processed/train/train_lmdb/train_lmdb/(*files in the downloaded train folder). It seems that there is still a path problem. How should I organize the training data? Thank you.

**Comment by YoungSeng** [comment]
No, ZEGGS data is processed means e.g. pruning, mirroring, etc. You still need to run the code `ZEGGS to lmdb`.

**Comment by zuob-1861523** [comment]
Thanks for replying. A follow-up for the problem. When running zeggs_data_to_lmdb.py, a segmentation fault (core dumped) occurs every time. My path is fine and I am running on an Nvidia A40 GPU on Red Hat Linux. Do you have any idea why this would happen? Thank you.

**Comment by sh-taheri** [comment]
> Thanks for replying. A follow-up

I have the same issue on my Linux system.

**Comment by YoungSeng** [comment]
I have two personal suggestions:

1. switch to a **different GPU machine**! Reconfigure the new process and the new environment to avoid a segmentation fault.

2. try [DiffuseStyleGesture+](https://github.com/YoungSeng/DiffuseStyleGesture/tree/master/BEAT-TWH-main#the-diffusestylegesture-entry-to-the-genea-challenge-2023), this code does not generate `lmdb` file but `h5` file.

Help it will be useful.

**Comment by sh-taheri** [comment]
Thanks for your advice, 
1. I was running the code on the debug mode and the issue did not happen (so didn't need to try suggestion1)
2. Also as you mentioned using the DiffuseStyleGesture+ works smoothly.

**Comment by YoungSeng** [comment]
@sh-taheri Glad to hear the problem was solved, in fact, I've had this problem solved by the first method, but I wasn't aware of why it would occasionally occur. Cheers.

**Comment by zuob-1861523** [comment]
Hi. I have been trying suggestion 2. Unfortunately, I am unable to solve the problem. When running process TWH code, there will still be a segmentation fault problem. But thanks for the help!
<img width="895" alt="Screenshot 2023-10-30 225217" src="https://github.com/YoungSeng/DiffuseStyleGesture/assets/46545230/1abb6ceb-4c9d-4972-a0cb-5d535cc8412c">

**Comment by YoungSeng** [comment]
That's a bit strange, you could try the first suggestion again.

In fact I don't really know how this error is caused, does anyone have any suggestions on how to fix this?

**Comment by zxk19981227** [comment]
I found the error for segment error. This happens for the package libsora. it could be solved by reading wav file with torchaudio

**Comment by sysu19351118** [comment]
作者你好，这个segmentation fault的错误我发现是什么原因了，只需要把./main/mydiffusion_zeggs/mfcc.py里面的import librosa
去掉就可以了，可能是librosa牵连着很多底层C++的东西，导致隔着文件引用就会出问题。。。
