### ISSUE TITLE
Auto Rig Pro

### ISSUE THREAD

**Issue by gavincapriola** [YoungSeng/DiffuseStyleGesture#15]
**Where can I find Auto Rig Pro software?**

In this video you say we will share software in GitHub project [YoungSeng / DiffuseStyleGesture] but I can't find it
https://www.youtube.com/watch?v=GdfeiyrTKY0

**Comment by YoungSeng** [comment]
Download link is here: `visualize_gesture_using_Blender.md`

**Comment by gavincapriola** [comment]
thanks
