### ISSUE TITLE
A question about predict_xstart

### ISSUE THREAD

**Issue by RobinWitch** [YoungSeng/DiffuseStyleGesture#17]
A nice job ! Helps me a lot! 
While I have a question, when I change [predict_xstart](https://github.com/YoungSeng/DiffuseStyleGesture/blob/f6ff4bf434b56367e86ca1f52b6312ee67c70989/main/utils/model_util.py#L67) from True to False , because I want to predict noise instead of signal , the result is bad , and train loss is 0.37 ,which is so high compared to predict_xstart=True !
Do you test this situation? Or could you give me some advice?

**Comment by YoungSeng** [comment]
Yes, but we are all predicting the original signal and not the noise. I have tried to change this parameter from `True` to `False` before and the results were really bad, I think it was the original MDM paper that didn't provide the code for predicting the noise correctly. Good luck.

**Comment by RobinWitch** [comment]
Thanks a lot!  If you have any new information or idea about this in the future , can you inform me ? thanks a lot again !

**Comment by YoungSeng** [comment]
Of course. No problem.
