### ISSUE TITLE
风格标签对生成的动作类型不是很管用

### ISSUE THREAD

**Issue by jiaqiAA** [YoungSeng/DiffuseStyleGesture#19]
对于同一个输入音频，我更换不同的风格标签（`style2onehot`），生成的动作类型并没有和标签一致，这个问题有什么解决办法吗？
训练数据我使用了不同的人（男生+女生），Zeroeggs是同一个人不同的风格，如果我想要标签的控制力度更强，是不是需要训练集是同一个人？现在生成的动作也会有不同的类型，但是他更倾向于输入的音频和哪个训练集类似，就生成对应的动作类型。

**Comment by YoungSeng** [comment]
不清楚“更倾向于输入的音频和哪个训练集类似，就生成对应的动作类型”是什么意思，我猜测你想问的是风格控制的效果不佳，我在BEAT上测试的效果也不如ZEGGS上明显，我认为这与数据集本身风格表演程度有关。另外输入的音频本身也是有风格的，所以尽量用中性的音频测试；另外音频的风格和控制的风格没有完全解耦开，也可以尝试增加风格控制的权重，例如将1修改为2或更高以控制风格。

**Comment by jiaqiAA** [comment]
谢谢您的回复。
是的，我的意思是风格控制效果不佳。风格是以特征的形式输入到模型里，增加风格控制的权重具体是怎么做呢？

**Comment by YoungSeng** [comment]
例如想生成明显old的手势，生成的时候可以将：

https://github.com/YoungSeng/DiffuseStyleGesture/blob/6ace14c82ac5084e3a41d1bb7dae0bc0060f1c39/main/mydiffusion_zeggs/sample.py#L24

改为：` 'Old':[0, 0, 0, 2, 0, 0], `
