### ISSUE TITLE
No such file or directory: '../../ubisoft-laforge-ZeroEGGS-main/data/processed_v1/processed/mean.npz'

### ISSUE THREAD

**Issue by fanhaidi** [YoungSeng/DiffuseStyleGesture#2]
Could you provide mean.npz and std.npz for Quick Start？Thank you

**Comment by YoungSeng** [comment]
Oops, thanks for finding this, I've uploaded it: `./ubisoft-laforge-ZeroEGGS-main/data/processed_v1`.
