### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ggg66** [YoungSeng/DiffuseStyleGesture#20]
当我运行python zeggs_data_to_lmdb.py时会出现段错误我用的是两张4090，环境是按照requirement配的，请问是内存不够还是环境有问题，感谢！

**Comment by YoungSeng** [comment]
1. I suggest trying it on another card, recreating the environment;
2. Try DiffuseStyleGesture+, generating the file for h5 instead of the lmdb file.
