### ISSUE TITLE
根节点位置漂移

### ISSUE THREAD

**Issue by Owen1234560** [YoungSeng/DiffuseStyleGesture#21]
非常感谢您的开源模型。
我问下，怎么较好地解决身体的根节点位置漂移问题？生成的动作身体漂移显得很不自然。我用提供的预训练模型和自己数据重新训练的模型，都或多或少存在这个问题。

**Comment by YoungSeng** [comment]
是的，也发现ZEGGS的数据表示训练出来存在这个问题，我建议：
1. 更换motion representation，尝试DiffuseStyleGesture+，漂移得到了部分改善；
2. 对下半身进行IK优化，可参考[UnifiedGesture](https://github.com/YoungSeng/UnifiedGesture/blob/master/retargeting/datasets/process_bvh.py#L312)

**Comment by Owen1234560** [comment]
好的，非常感谢大佬支持
