### ISSUE TITLE
在写bvh文件时出现错误

### ISSUE THREAD

**Issue by jiaqiAA** [YoungSeng/DiffuseStyleGesture#22]
你好，我在使用`DiffuseStyleGesture+`进行推理时，写bvh出现了问题，涉及到的代码为[code](https://github.com/YoungSeng/DiffuseStyleGesture/blob/master/BEAT-TWH-main/process/pymo/writers.py#L57), 列表`self.motions_`前6个元组的形状为（num_frame, 2），其余为（num_frame,），由于形状不一样，在`self.motions_ = np.asarray(self.motions_).T`时出现了错误，你知道这个是什么原因吗，怎么解决呢？

**Comment by YoungSeng** [comment]
请问是Quick start吗？请问有修改过代码吗？以及可以提供运行哪一个代码、更多报错细节我来看一看。

**Comment by jiaqiAA** [comment]
使用BEAT数据的Quick start是没有问题的，使用我自己的数据训练的模型出现了问题。我怀疑是[这里](https://github.com/YoungSeng/DiffuseStyleGesture/blob/master/BEAT-TWH-main/process/process_BEAT_bvh.py#L127)出现了问题，导致在root节点读取上出现了问题，[`X.values['%s_%s'%(joint,cn)].values`](https://github.com/YoungSeng/DiffuseStyleGesture/blob/master/BEAT-TWH-main/process/pymo/writers.py#L57)形状为（num_frame, 2），children为（num_frame,）。

**Comment by YoungSeng** [comment]
使用自己的数据确实可能会有问题，因为不同动补格式的bvh文件处理起来代码不一样，你可以看看[DiffuseStyleGesture](https://github.com/YoungSeng/DiffuseStyleGesture)的ZEGGS数据集以及DiffuseStyleGesture+的BEAT数据集和TWH数据集的bvh文件处理bvh和写bvh的代码进行参考。

**Comment by jiaqiAA** [comment]
为了提高模型在音频上的泛化性，请问您有什么好的建议吗？另外，有测试[WavLM Large](https://github.com/microsoft/unilm/tree/master/wavlm)和wav2vec哪个效果好一些吗。最后，我没找到文章里提到的metric，请问这部分有代码可以参考吗？

**Comment by YoungSeng** [comment]
泛化性不太清楚没有做过实验，或许预训练模型提特征可以试试；WavLM Large我实验感觉还可以；客观评价可参考[这个](https://github.com/YoungSeng/UnifiedGesture/issues/3)，主观评价可参考[这个](https://github.com/YoungSeng/DiffuseStyleGesture/issues/16)
