### ISSUE TITLE
关于指标评测的一些问题

### ISSUE THREAD

**Issue by dsdf783** [YoungSeng/DiffuseStyleGesture#24]
你好，
论文中提到FGD的评测结果，请问是否可以提供FGD的评测脚本，以便复现实验结果，谢谢！

**Comment by YoungSeng** [comment]
很抱歉，由于我已经从实习公司离职，目前无法提供计算FGD所使用的Auto Encoder。

**Comment by dsdf783** [comment]
DiffuseStyleGesture+中对BEAT数据集进行处理的代码是否可以提供一下，audio、gesture、text对应的.npy文件是如何生成的？

**Comment by YoungSeng** [comment]
代码中已经提供：https://github.com/YoungSeng/DiffuseStyleGesture/tree/master/BEAT-TWH-main#41-beat-dataset
