### ISSUE TITLE
Issues with both hands are turned against each other

### ISSUE THREAD

**Issue by hmthanh** [YoungSeng/DiffuseStyleGesture#25]
Thank for effort with project Gesture Generation.

I have issues when visualization with following .bvh file generated.
Here is my configuration:

- Blender version: `3.6.5`
- Auto-Rig Pro version: `3.68.14`
- Generated gesture: 
[https://1drv.ms/f/s!AvSTDY2o11xHgalWGd7PGtdj5yOiRA?e=xek1oW](https://1drv.ms/f/s!AvSTDY2o11xHgalWGd7PGtdj5yOiRA?e=xek1oW)

Issues is following image:

Both hands are are turned against each other
![image](https://github.com/YoungSeng/DiffuseStyleGesture/assets/8927701/6502c981-61fd-45fe-b054-b51b9c891f7b)

I almost try many thing and many times on blender but it's still not work. I have try Rokoko Matching with skeleton also.
I just wonder it's could be wrong with bones generated or the position of bones when using Auto-Rig Pro.

Could you check the visualation of bvh file result again with my bvh file for figure out what problem with my visualization.

**Comment by hmthanh** [comment]
HI @YoungSeng ,
Event with correct all Bone in Bones List.

![image](https://github.com/YoungSeng/DiffuseStyleGesture/assets/8927701/b4976f3a-78e5-46ad-8186-dda30f32a273)

It's still retarget a wrong bones.

![image](https://github.com/YoungSeng/DiffuseStyleGesture/assets/8927701/7f2adbe4-589a-4e08-a786-f6bd9b36df02)

**Comment by YoungSeng** [comment]
Thank you for your question and email reminding me, I have updated the instructions in `visualize_gesture_using_Blender.md` ([here](https://github.com/YoungSeng/DiffuseStyleGesture/blob/master/visualize_gesture_using_Blender.md)), please check it out, good wishes.

**Comment by hmthanh** [comment]
Thank you @YoungSeng 
This is my fault because I didn't look at the markdown carefully.
Thanks, again
