### ISSUE TITLE
关于风格强度调节参数gamma的问题

### ISSUE THREAD

**Issue by Jeremy8080** [YoungSeng/DiffuseStyleGesture#27]
hi，你们的研究成果真的很棒，同时有些问题我想请教一下
您的文章中提到，通过调节gamma可以实现对风格化强度的调节，但在工程中没有看到具体的可实现调节的接口，请问这个编辑方式在工程内有具体实现吗

**Comment by YoungSeng** [comment]
感谢对此工作感兴趣，在Readme的最后一行有更新过：please refer to https://github.com/YoungSeng/DiffuseStyleGesture/issues/8#issuecomment-1620027786 to set the style and intensity you want.

在采样的时候指定一下风格和对应的强度就可以了，抱歉没有提供此接口还需要自己小改一下：
https://github.com/YoungSeng/DiffuseStyleGesture/blob/85f4096c1784fbc1ffe52cfa9cf3ca653fcef9c9/main/mydiffusion_zeggs/sample.py#L378-L381
