### ISSUE TITLE
Questions on Clipping inputs

### ISSUE THREAD

**Issue by Ying156209** [YoungSeng/DiffuseStyleGesture#31]
Hi, 
Real Nice Work!   I have a question about [clip_len](https://github.com/YoungSeng/DiffuseStyleGesture/blob/f78242bbdeca945a3f15f44b1e0497a8b6bdbfea/BEAT-TWH-main/process/process_TWH_bvh.py#L346) here.  Wav is in 16000Hz, and both text and gesture are in 30fps.   Do I miss something?   Thx!!

**Comment by Ying156209** [comment]
I see. They are all around 30fps.    https://github.com/YoungSeng/DiffuseStyleGesture/blob/f78242bbdeca945a3f15f44b1e0497a8b6bdbfea/BEAT-TWH-main/process/tool.py#L21

**Comment by YoungSeng** [comment]
Yeah, in fact DiffuseStyleGesture and plus as in the paper are finally aligned with linear interpolation in the time dimension, take a look at the code.
