### ISSUE TITLE
About the result of DDIM？

### ISSUE THREAD

**Issue by liushao** [YoungSeng/DiffuseStyleGesture#35]
Hello, theoretically using DDIM can reduce the step of the sampler. However, using DDIM sampling in the program and reducing the step to 100 would result in a significant difference from the effect of step=1000? The gesture motion amplitude with step=100 under DDIM is very small.

Thanks very much！

**Comment by YoungSeng** [comment]
I haven't tried DDIM. I've also only used 100 steps while debugging, but of course 1000 steps is better, 100 steps doesn't seem to make sense.

**Comment by liushao** [comment]
Please， the function "ddim_sample_loop()" in engineering is not debugged?

**Comment by YoungSeng** [comment]
This code is modified from MDM, check [this](https://github.com/GuyTevet/motion-diffusion-model/issues/76).

**Comment by liushao** [comment]
Thanks, I am already debugging it myself

**Comment by liushao** [comment]
closed
