### ISSUE TITLE
Retargetting

### ISSUE THREAD

**Issue by ylhua** [YoungSeng/DiffuseStyleGesture#40]
Hi, thanks for your great work!! I followed your tutorial for retargeting the pose and got this weird result. It seems like the pose of hands are opposite with the original pose. Do you have some ideas to fix this ?
<img width="441" alt="Screenshot 2024-06-21 at 15 16 42" src="https://github.com/YoungSeng/DiffuseStyleGesture/assets/37425013/2a284aab-1849-4f80-a68a-270f3eec050b">

**Comment by ylhua** [comment]
And this is my bvh file
[20240621_032628_smoothing_SG_minibatch_320_[1, 0, 0, 0, 0, 0]_123456.bvh.zip](https://github.com/user-attachments/files/15924197/20240621_032628_smoothing_SG_minibatch_320_.1.0.0.0.0.0._123456.bvh.zip)

**Comment by YoungSeng** [comment]
See here: https://github.com/YoungSeng/DiffuseStyleGesture/blob/master/visualize_gesture_using_Blender.md

**Comment by ylhua** [comment]
Thanks, got it!
