### ISSUE TITLE
How many epochs should I set to reproduce the results when training？

### ISSUE THREAD

**Issue by fanhaidi** [YoungSeng/DiffuseStyleGesture#6]
In DiffuseStyleGesture.yml, epoch is set to 500. 
but in training_loop.py, self.num_epochs is set to 40000

**Comment by YoungSeng** [comment]
Yes and modify this: https://github.com/YoungSeng/DiffuseStyleGesture/blob/c1ae3934fa24b98e6b85920953d3e8d255139ed7/main/train/training_loop.py#L48

Please ignore some parameters in the .yml file, I don't use them.
