### ISSUE TITLE
Question of motion representation

### ISSUE THREAD

**Issue by cyk990422** [YoungSeng/DiffuseStyleGesture#7]
Sorry, I still have a doubt, why not learn the Euler angles of the local rotation in the motion representation, is it because this representation is difficult to learn?

**Comment by cyk990422** [comment]
Another problem is that I noticed that when you save bvh, in the code of converting quaternion to Euler angle, the prompt can only be converted to Euler angle in zyx and xzy order, whether it can not be converted to Euler in xyz order horn? I tried to write a conversion process myself (convert the Euler angles in the xyz order to quaternions and then back to the Euler angles in the same order), but it seems that the angle value of the Euler angles has changed? Thank you very much for your patient reply!

**Comment by YoungSeng** [comment]
Hey cyk,

I think the representations of motion are all right!

For examples, [End2End](https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/tree/master) used [rotation matrix](https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/blob/46671fc6af8a3dbcb93cdafca4f07bc064a2c3b1/scripts/twh_dataset_to_lmdb.py#L44) and [Audio2Repr2Gesture](https://github.com/GestureGeneration/Speech_driven_gesture_generation_with_autoencoder) used [position](https://github.com/GestureGeneration/Speech_driven_gesture_generation_with_autoencoder/blob/59e8ebdb0f6e87b0e81268046c99a4d6c9bf62a8/data_processing/create_vector.py#L232) or [exponential maps](https://github.com/genea-workshop/Speech_driven_gesture_generation_with_autoencoder/tree/GENEA_2022), [QuaterNet](https://arxiv.org/abs/1805.06485) used quaternions...

Although these can switch to each other, however, rotation is easy to calculate rotational velocity and acceleration. 

Although position, positional velocity, and positional acceleration or rotation and rotational velocity and acceleration are contained to each other, more modalities are better, see https://github.com/sebastianstarke/AI4Animation/issues/47#issuecomment-945189038

That is why Zeroeggs used complex [motion representation](https://github.com/ubisoft/ubisoft-laforge-ZeroEGGS/blob/4992d9ab5e28bc4bb13219a598906562f5786448/ZEGGS/data_pipeline.py#L211). 

All in all, I think motion representation is not key in gesture generation. You may take some experiments on them.

Wish it will help you : )

**Comment by YoungSeng** [comment]
The `bvh` processing pipeline and writing pipeline are the same as [Zeroeggs](https://github.com/ubisoft/ubisoft-laforge-ZeroEGGS), which is not familiar to me. You may check the source code in Zeroeggs.

**Comment by cyk990422** [comment]
Ok, I see, thank you very much for your reply, it helped me a lot.
